FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["my-account-api.csproj", "."]
RUN dotnet restore "my-account-api.csproj"
COPY . .
RUN dotnet build "my-account-api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "my-account-api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080
ENTRYPOINT ["dotnet", "my-account-api.dll"]